version: '2'

services:
  chronograf:
    image: quay.io/influxdb/chronograf:latest
    ports:
      - "8888:8888"
  influxdb:
    image: influxdb:1.1.1
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influx:rw
  kapacitor:
    image: kapacitor:1.1.1
    ports:
      - "9092:9092"
    volumes:
      - ./data/kapacitor:/var/lib/kapacitor:rw
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf
  telegraf:
    image: telegraf:1.1.2
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    links:
      - influxdb:influxdb
